FROM mongo:latest
MAINTAINER wichan7@naver.com

ARG MONGO_PORT="27017"
ARG MONGO_REPLICA_ROLE="primary"
ARG PRIMARY_NAME="mongo-primary-0"

ENV ENV_MONGO_PORT=$MONGO_PORT
ENV ENV_MONGO_REPLICA_ROLE=$MONGO_REPLICA_ROLE
ENV ENV_PRIMARY_NAME=$PRIMARY_NAME

EXPOSE $MONGO_PORT